id: redloop_orchestrator_v1
namespace: redloop.security

description: |
  RedLoop Security Assessment - AI-Powered Vulnerability Scanner
  Streams progress, logs, and AI outputs via webhooks for real-time UI

labels:
  project: redloop
  type: security-scan
  version: v1

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "redloop_secret"

inputs:
  - id: repository_url
    type: STRING
    description: "GitHub repository URL to analyze"
    required: true
  
  - id: branch
    type: STRING
    defaults: "main"
    description: "Branch to analyze"

# Variables for reuse - hardcoded backend URL for reliability
variables:
  backend_url: "http://redloop-backend:8000"

tasks:
  # ============================================================================
  # NOTIFY START
  # ============================================================================
  - id: notify_start
    type: io.kestra.plugin.core.http.Request
    allowFailure: true
    uri: "{{ vars.backend_url }}/webhook/task-update"
    method: POST
    contentType: application/json
    body: |
      {"execution_id": "{{ execution.id }}", "task_id": "start", "status": "RUNNING", "message": "🚀 Starting scan for {{ trigger.body.repository_url ?? inputs.repository_url }} ({{ trigger.body.branch ?? inputs.branch }})"}

  # ============================================================================
  # WORKING DIRECTORY - All agents run inside this block for direct data access
  # ============================================================================
  - id: working_directory
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      # Step 1: Clone the repository
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        url: "{{ trigger.body.repository_url ?? inputs.repository_url }}"
        branch: "{{ trigger.body.branch ?? inputs.branch }}"
        timeout: PT2M

      # Step 2: Read code files
      - id: read_code
        type: io.kestra.plugin.scripts.shell.Commands
        timeout: PT1M
        commands:
          - |
            FILE_COUNT=$(find . -type f \( -name "*.py" -o -name "*.js" -o -name "*.ts" -o -name "*.java" -o -name "*.go" \) | grep -v node_modules | grep -v .git | wc -l)
            echo "Found $FILE_COUNT code files"
            for f in $(find . -type f \( -name "*.py" -o -name "*.js" -o -name "*.ts" -o -name "*.java" -o -name "*.go" \) | grep -v node_modules | grep -v .git | head -20); do
              echo "=== FILE: $f ==="
              head -150 "$f"
              echo ""
            done > code_content.txt
            echo "Prepared $FILE_COUNT files for analysis"
        outputFiles:
          - code_content.txt

      # Step 3: ADVERSARY AGENT - Find vulnerabilities
      - id: adversary_agent
        type: io.kestra.plugin.ai.agent.AIAgent
        description: "Red Team - Find vulnerabilities"
        timeout: PT5M
        retry:
          type: constant
          maxAttempt: 2
          interval: PT10S
        provider:
          type: io.kestra.plugin.ai.provider.GoogleGemini
          apiKey: "{{ secret('GEMINI_API_KEY') }}"
          modelName: gemini-2.5-flash
        prompt: |
          Analyze the following code for security vulnerabilities:
          
          {{ read(outputs.read_code.outputFiles['code_content.txt']) }}
          
          Output your findings as JSON:
          {
            "vulnerabilities": [
              {
                "id": "VULN-001",
                "type": "SQL Injection",
                "severity": "CRITICAL",
                "file": "path/to/file.py",
                "line": 42,
                "vulnerable_code": "the vulnerable code",
                "payload": "attack payload",
                "fix_suggestion": "how to fix"
              }
            ],
            "summary": {
              "total_vulnerabilities": 1,
              "critical": 1,
              "high": 0,
              "medium": 0,
              "low": 0
            },
            "recommendation": "BLOCK"
          }
        systemMessage: |
          You are ADVERSARY, a red team security researcher.
          Find vulnerabilities: SQL injection, XSS, RCE, auth flaws, etc.
          Be thorough and specific with payloads.

      # Step 4: SUMMARIZER AGENT - Make BLOCK/PASS decision
      - id: summarizer_agent
        type: io.kestra.plugin.ai.agent.AIAgent
        description: "Summarize vulnerabilities and make BLOCK/PASS decision"
        timeout: PT3M
        retry:
          type: constant
          maxAttempt: 2
          interval: PT10S
        provider:
          type: io.kestra.plugin.ai.provider.GoogleGemini
          apiKey: "{{ secret('GEMINI_API_KEY') }}"
          modelName: gemini-2.5-flash
        prompt: |
          Analyze the vulnerability report and make a deployment decision:
          
          ************************************************************
          *            ADVERSARY FINDINGS TO ANALYZE                 *
          ************************************************************
          {{ outputs.adversary_agent.textOutput | default('No vulnerability scan results available - upstream task may have failed.') }}
          ************************************************************
          
          Provide your analysis as JSON:
          {
            "summary": "2-3 sentence executive summary",
            "risk_score": 7,
            "decision": "BLOCK",
            "reasoning": "why this decision was made",
            "vulnerability_counts": {
              "critical": 2,
              "high": 1,
              "medium": 3,
              "low": 0,
              "total": 6
            },
            "priority_fixes": ["fix 1", "fix 2", "fix 3"]
          }
          
          Decision Rules:
          - BLOCK if any CRITICAL or 3+ HIGH vulnerabilities
          - PASS otherwise
        systemMessage: |
          You are a Security Analyst making deployment decisions.
          Be decisive. Always include BLOCK or PASS decision.

      # Step 5: DEFENDER AGENT - Generate security fixes
      - id: defender_agent
        type: io.kestra.plugin.ai.agent.AIAgent
        description: "Blue Team - Generate security fixes"
        timeout: PT5M
        retry:
          type: constant
          maxAttempt: 2
          interval: PT10S
        provider:
          type: io.kestra.plugin.ai.provider.GoogleGemini
          apiKey: "{{ secret('GEMINI_API_KEY') }}"
          modelName: gemini-2.5-flash
        prompt: |
          Generate fixes for these vulnerabilities:
          
          VULNERABILITIES:
          {{ outputs.adversary_agent.textOutput | default('No vulnerability data available.') }}
          
          CODE:
          {{ read(outputs.read_code.outputFiles['code_content.txt']) }}
          
          Provide fixes as JSON:
          {
            "fixes": [
              {
                "vulnerability_id": "VULN-001",
                "file": "path/to/file.py",
                "original_code": "vulnerable code",
                "fixed_code": "secure code",
                "explanation": "why this fix works"
              }
            ],
            "summary": {
              "total_fixed": 5,
              "success_rate": "83%"
            }
          }
        systemMessage: |
          You are DEFENDER, a blue team security engineer.
          Generate production-ready secure code fixes.

      # Step 6: FINAL REPORT - Executive summary
      - id: final_report
        type: io.kestra.plugin.ai.agent.AIAgent
        description: "Generate executive summary"
        timeout: PT3M
        provider:
          type: io.kestra.plugin.ai.provider.GoogleGemini
          apiKey: "{{ secret('GEMINI_API_KEY') }}"
          modelName: gemini-2.5-flash
        prompt: |
          Generate a final security assessment report:
          
          Repository: {{ trigger.body.repository_url ?? inputs.repository_url }}
          
          ADVERSARY FINDINGS:
          {{ outputs.adversary_agent.textOutput | default('No adversary findings available.') }}
          
          SUMMARIZER DECISION:
          {{ outputs.summarizer_agent.textOutput | default('No risk analysis available.') }}
          
          DEFENDER FIXES:
          {{ outputs.defender_agent.textOutput | default('No security fixes available.') }}
          
          Create a concise executive summary in markdown with:
          1. Overall security posture
          2. Key findings (top 3)
          3. Recommended actions
          4. Deployment recommendation
        systemMessage: |
          You are a security analyst creating executive reports.
          Be concise and actionable.

  # ============================================================================
  # WEBHOOK NOTIFICATIONS - Send updates to backend after each major step
  # ============================================================================
  - id: notify_adversary_done
    type: io.kestra.plugin.core.http.Request
    allowFailure: true
    uri: "{{ vars.backend_url }}/webhook/task-update"
    method: POST
    contentType: application/json
    body: |
      {"execution_id": "{{ execution.id }}", "task_id": "adversary_agent", "status": "SUCCESS", "message": "🔴 Adversary scan complete", "output": "{{ outputs.working_directory.adversary_agent.textOutput | default('No output') | replace('\"', '\\\"') | replace('\n', ' ') }}"}

  - id: notify_summarizer_done
    type: io.kestra.plugin.core.http.Request
    allowFailure: true
    uri: "{{ vars.backend_url }}/webhook/task-update"
    method: POST
    contentType: application/json
    body: |
      {"execution_id": "{{ execution.id }}", "task_id": "summarizer_agent", "status": "SUCCESS", "message": "📋 Risk assessment complete", "output": "{{ outputs.working_directory.summarizer_agent.textOutput | default('No output') | replace('\"', '\\\"') | replace('\n', ' ') }}"}

  - id: notify_defender_done
    type: io.kestra.plugin.core.http.Request
    allowFailure: true
    uri: "{{ vars.backend_url }}/webhook/task-update"
    method: POST
    contentType: application/json
    body: |
      {"execution_id": "{{ execution.id }}", "task_id": "defender_agent", "status": "SUCCESS", "message": "🛡️ Security fixes generated", "output": "{{ outputs.working_directory.defender_agent.textOutput | default('No output') | replace('\"', '\\\"') | replace('\n', ' ') }}"}

  - id: notify_complete
    type: io.kestra.plugin.core.http.Request
    allowFailure: true
    uri: "{{ vars.backend_url }}/webhook/execution-update"
    method: POST
    contentType: application/json
    body: |
      {"execution_id": "{{ execution.id }}", "state": "SUCCESS", "message": "✅ Security assessment complete!"}

  - id: complete
    type: io.kestra.plugin.core.log.Log
    message: "RedLoop Security Assessment Complete!"

errors:
  - id: error_log
    type: io.kestra.plugin.core.log.Log
    message: "Flow execution failed"
  
  - id: notify_error
    type: io.kestra.plugin.core.http.Request
    allowFailure: true
    uri: "http://redloop-backend:8000/webhook/execution-update"
    method: POST
    contentType: application/json
    body: |
      {"execution_id": "{{ execution.id }}", "state": "FAILED", "message": "❌ Scan failed - check Kestra logs for details"}
