#!/bin/bash
set -e

ENV_FILE="${1:-.env}"
OUTPUT_FILE="${2:-.env_encoded}"

if [ ! -f "$ENV_FILE" ]; then
    echo "Error: $ENV_FILE file not found!"
    echo "Usage: ./encode_secrets.sh [input_file] [output_file]"
    exit 1
fi

echo "# Kestra encoded secrets - auto-generated from $ENV_FILE" > "$OUTPUT_FILE"
echo "# Do not edit this file directly, edit $ENV_FILE instead" >> "$OUTPUT_FILE"
echo "# Generated: $(date -Iseconds)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

count=0
while IFS= read -r line || [ -n "$line" ]; do
    # Skip empty lines and comments
    if [ -z "$line" ] || [[ "$line" =~ ^[[:space:]]*# ]]; then
        continue
    fi
    
    # Skip lines without =
    if [[ ! "$line" =~ = ]]; then
        continue
    fi
    
    # Extract key and value (handle values with = signs)
    key="${line%%=*}"
    value="${line#*=}"
    
    # Remove leading/trailing whitespace from key
    key=$(echo "$key" | xargs)
    
    # Skip if key is empty
    if [ -z "$key" ]; then
        continue
    fi
    
    # Remove surrounding quotes from value if present
    value="${value#\"}"
    value="${value%\"}"
    value="${value#\'}"
    value="${value%\'}"
    
    # Base64 encode the value
    encoded=$(echo -n "$value" | base64 -w 0 2>/dev/null || echo -n "$value" | base64)
    
    echo "SECRET_$key=$encoded" >> "$OUTPUT_FILE"
    ((count++))
done < "$ENV_FILE"

echo ""
echo "✅ Generated $OUTPUT_FILE with $count secrets"
echo ""
echo "Contents:"
cat "$OUTPUT_FILE"
