#!/bin/bash
# Script to generate .env_encoded from .env for Kestra secrets
# Kestra requires SECRET_ prefix and base64-encoded values

if [ ! -f .env ]; then
    echo "Error: .env file not found!"
    exit 1
fi

echo "# Kestra encoded secrets - auto-generated from .env" > .env_encoded
echo "# Do not edit this file directly, edit .env instead" >> .env_encoded
echo "" >> .env_encoded

while IFS='=' read -r key value; do
    if [ -z "$key" ] || [[ "$key" == \#* ]]; then
        continue
    fi
    encoded=$(echo -n "$value" | base64 -w 0)
    echo "SECRET_$key=$encoded" >> .env_encoded
done < .env

echo "Generated .env_encoded successfully!"
cat .env_encoded
